name: Community Label Issue

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  triage:
    runs-on: ubuntu-latest
    name: Label Issue - Community

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
      - name: Install python requests
        run: pip install requests
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: See if the user is a community member
        uses: jannekem/run-python-script-action@v1
        id: check_user
        with:
          script: |
            import requests
            print(${{ github.event }})
            user_token = '${{ secrets.GITHUB_TOKEN }}'
            response = requests.get('https://api.github.com/orgs/ansible/repos?type=private', headers={'Accept': 'application/vnd.github+json', 'Authorization': 'token {}'.format(user_token)})
            if len(response.json()) > 0:
                print("ansible member")
            else:
                print("community member")
                response = requests.post('https://api.github.com/repos/ansible/awx/issues/{issue_number}/labels', json={"labels":["community"]}, headers={'Accept': 'application/vnd.github+json', 'Authorization': 'token {}'.format(user_token)})
