on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: '/recheck'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - uses: actions/checkout@v2
        if: steps.check.outputs.triggered == 'true'

      - uses: john-westcott-iv/github-file-test/.github/workflows/ci.yml@main
        if: steps.check.outputs.triggered == 'true'

